FROM mhart/alpine-node:latest

MAINTAINER datarhei <info@datarhei.org>

RUN apk update
RUN apk --no-cache add --update ffmpeg nginx git

COPY . /restreamer
WORKDIR /restreamer

RUN npm install -g bower grunt-cli public-ip eslint@v2.0.0-beta.3 && \
    npm install && \
    grunt build && \
    npm prune --production && \
    npm cache clean && \
    bower cache clean --allow-root && \
    apk del git

ENV RESTREAMER_USERNAME admin
ENV RESTREAMER_PASSWORD datarhei

# temp hack
RUN mkdir /usr/local/nginx /usr/local/nginx/conf /usr/local/nginx/sbin && \
    ln -s /etc/nginx/mime.types /usr/local/nginx/conf/mime.types && \
    ln -s /usr/sbin/nginx /usr/local/nginx/sbin/nginx

EXPOSE 8080
VOLUME ["/restreamer/db"]

CMD ["./run.sh"]
